// Stamps one build identity into lib/build-info.ts before every build.
//
// WHY THIS FILE EXISTS. The build id used to be computed inside
// next.config.mjs as Date.now(), and that config is evaluated more than once:
// the browser bundle took its value from one evaluation and the server route
// took its value from another. They disagreed, so the app compared its own id
// against the server's, found a difference that was never real, and announced
// "A new version is ready" forever. An update prompt that is always on is worse
// than no prompt, because people learn to ignore it.
//
// Writing the value to a file makes it a compiled-in constant on both sides.
// One build, one id, no clock involved, nothing left to evaluate twice.
//
// HOSTING. This reads the environment variables the common hosts already set,
// and falls back to a timestamp when it recognises none of them — so it works
// on Vercel, Netlify, Cloudflare Pages, GitHub Actions, a container, or a
// laptop, with nothing to configure anywhere.
//
// A commit sha is preferred over a timestamp because redeploying the same code
// then keeps the same id, and nobody is told to update to what they are already
// running. Set BUILD_ID yourself to override everything below.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const env = process.env;

// First match wins. Add your host here if it is not listed — one line.
const sha = (
  env.BUILD_ID ||
  env.VERCEL_GIT_COMMIT_SHA ||       // Vercel
  env.COMMIT_REF ||                  // Netlify
  env.CF_PAGES_COMMIT_SHA ||         // Cloudflare Pages
  env.GITHUB_SHA ||                  // GitHub Actions
  env.CI_COMMIT_SHA ||               // GitLab CI
  env.SOURCE_VERSION ||              // Heroku, Render
  ''
).slice(0, 12);

const id = sha || Date.now().toString(36);
const time = new Date().toISOString();

// WHICH DEPLOYMENT THIS IS, and where the real one lives.
//
// This is what stops a person ending up with two copies of the app installed.
// A preview deployment gets its own hostname, and a different hostname is a
// different app to the browser: its own install, its own service worker, its own
// storage. Open a preview link, accept the install prompt, and you now have a
// second icon that can never receive a production update, because production is
// a different origin entirely. That is not hypothetical; it happened.
//
// So a preview refuses to be installed (components/InstallPrompt.tsx) and points
// at the real address instead of guessing it from the hostname.
//
// `BUILD_ENV` must be exactly 'production', 'preview' or 'development'.
const rawEnv =
  env.BUILD_ENV ||
  env.VERCEL_ENV ||                                        // Vercel: all three
  (env.CONTEXT === 'production'                            // Netlify
    ? 'production'
    : env.CONTEXT
      ? 'preview'
      : '') ||
  (env.CF_PAGES_BRANCH                                     // Cloudflare Pages
    ? env.CF_PAGES_BRANCH === 'main'
      ? 'production'
      : 'preview'
    : '') ||
  'development';

const buildEnv = ['production', 'preview', 'development'].includes(rawEnv)
  ? rawEnv
  : 'development';

// A CHURCH CAN HAVE MORE THAN ONE REAL ADDRESS, and for a while it must.
//
// Moving to a custom domain is not an instant. There is a period -- weeks,
// usually -- when the old address and the new one are both genuinely the app,
// both serve the same deployment, and both keep updating. The app used to
// permit exactly one, so the moment a custom domain became production the OLD
// address stopped offering the install and Settings told everybody still on it
// that they were looking at a preview which "can never receive an update".
//
// That is false, and it is aimed squarely at the people who installed earliest.
//
// So this is a LIST. Set CANONICAL_HOST to one host or several, comma
// separated. What it must never contain is a per-deployment URL: those are
// unique to one build and an app installed from one can genuinely never
// update, which is the whole reason this check exists.
const canonical = (
  env.CANONICAL_HOST ||
  env.VERCEL_PROJECT_PRODUCTION_URL ||
  env.NETLIFY_PRODUCTION_URL ||
  ''
)
  .split(',')
  .map((h) => h.trim().replace(/^https?:\/\//, '').replace(/\/+$/, ''))
  .filter(Boolean);

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'lib', 'build-info.ts');

writeFileSync(
  out,
  `// GENERATED by scripts/stamp-build.mjs before every build. Do not edit.
// One value per build, imported by both the browser bundle and the server route
// so the two can never disagree about which build is running.
export const BUILD_ID = ${JSON.stringify(id)};
export const BUILD_TIME = ${JSON.stringify(time)};
// Typed as the union, not as the one literal that happens to be stamped today.
// Without the annotation TypeScript narrows this to a single string and then
// rejects every comparison against the other two as "no overlap", which fails
// the build on whichever environment is not the one last stamped locally.
export const BUILD_ENV: 'production' | 'preview' | 'development' = ${JSON.stringify(buildEnv)};
/** Every host that is really this app. The first is the one to share. */
export const CANONICAL_HOSTS: string[] = ${JSON.stringify(canonical)};
/** The address to hand somebody. Empty when nothing was configured. */
export const CANONICAL_HOST: string = ${JSON.stringify(canonical[0] ?? '')};
`,
);

console.log(
  `build stamped: ${id} (${time}) env=${buildEnv} canonical=${canonical || '(none)'}`,
);
